---
title: "Bernie Sanders contributions (2016-2017)."
author: "Kris Anaya"
date: "5/22/2017"
output: html_document
---

### load packages
```{r echo=FALSE, message=False, warning=False, packages}
#install.packages("stringr")
#install.packages(c("maps","mapdata"))
#install.packages("ggmap")

library(mapdata)
library(maps)
library(ggmap)
library(ggplot2)
library(dplyr)
library(GGally)
library(scales)
library(memisc)
library(gridExtra)
library(grid)
library(RColorBrewer)
library('bitops')
library('RCurl')


setwd("/Users/Anaya/repos/udacity_data_analyst/project_4/src") # set my directory. 
```

# Bernie-Trump Dataset

thoughts: I discovered that there are refund amounts within the data set. Which threw me off.

```{r echo=False, Load_the_Data}
############################################# Map Datasets ##########################################################
counties <- map_data("county")
ca_county <-subset(counties, region == "california")

#create a unique datafram using google long and lat queries. 
cities <- as.data.frame(unique(bsdf$city))
names(cities)[names(cities) == 'unique(bsdf$city)'] <- 'city'
cities$city_state <- paste(as.character(cities$city), "CA", sep=", ") 
cities.new <- cbind(geocode(as.character(cities$city_state)), cities)
write.csv(cities.new, file = "California_geoLocation_new.csv",row.names=FALSE)

## filling in columns with matching IDs from two dataframes in R
# Source: http://stackoverflow.com/questions/25539326/filling-in-columns-with-matching-ids-from-two-dataframes-in-r
geoloc <- read.csv('California_geoLocation_new.csv', row.names=NULL) #load dataset

############################################# Bernie Dataset ######################################################

bsdf <- read.csv(file = "P60007168-CA.csv", sep = ",", header = FALSE)

colnames(bsdf) <- c("cmte_id", "cand_it", "canidate", "name",
                    "city", "state", "zip", 
                    "employer", "occupation",
                    "amount", "date",
                    "receipt", "memo",
                    "memo_text", "form_tp", "file_number",
                    "tan_id", "election_tp") # rename columns 

bsdf  = bsdf[-1,] #drop first row in dataset

myvars <- c("name","canidate","city","state","zip","employer","occupation","amount","date","receipt") #create data columns

bsdf <- bsdf[myvars] #pick columns I need. 


bsdf$amount <- as.numeric(as.character(bsdf$amount)) #change amount to numeric
bsdf$zip <- as.numeric(as.character(bsdf$zip)) #change zip to numeric#change date
bsdf$date <- strptime(bsdf$date, "%d-%b-%y")
bsdf$date <- as.POSIXlt(bsdf$date)

nm <- c("lon", "lat") #add lat long 
bsdf[nm] <- lapply(nm, function(x) geoloc[[x]][match(as.character(bsdf$city), as.character(geoloc$city))]) #create loc dataset 

set.seed(20000)
sample_bernie <- bsdf[sample(1:length(bsdf$amount), 3000), ] #sample dataset for bernie

#subset dataframes 

largest_cities_bsdf <- subset(bsdf, city == c("SAN FRANCISCO", "SAN JOSE", "LOS ANGELES","SACRAMENTO","SAN DIEGO", "OAKLAND",
                                              "BERKELEY")) #sanders contributions in bigger cities

refund_bsdf <- subset(bsdf, receipt == "Refund" & city == c("SAN FRANCISCO", "SAN JOSE", "LOS ANGELES","SACRAMENTO","SAN DIEGO", "OAKLAND",
                                              "BERKELEY")) # largest cities who obtained a refund.


largest_amount_bsdf <- subset(largest_cities_bsdf, amount > 0) #no refunds in dataset

head(bsdf) # look at dataset


############################################# Trump Dataset ######################################################

dtdf <- read.csv("P80001571-CA.csv", sep = ",", header = FALSE)

colnames(dtdf) <- c("cmte_id", "cand_id", "canidate", "name","city", "state", "zip", "employer", "occupation", "amount", "date","receipt", "memo","memo_text", "form_tp", "file_number","tran_id", "election_tp") # rename columns 


dtdf = dtdf[-1,] #drop first row
myvars <- c("name","canidate","city","state","zip","employer","occupation","amount","date","receipt") #create data columns
dtdf <- dtdf[myvars] #choose columns i'm interested in.

dtdf$amount <- as.numeric(as.character(dtdf$amount)) #change amount to numeric
dtdf$zip <- as.numeric(as.character(dtdf$zip)) #change zip to numeric#change date
dtdf$date <- strptime(dtdf$date, "%d-%b-%y") #fix date
dtdf$date <- as.POSIXlt(dtdf$date) #fix date

nm <- c("lon", "lat") #add lat and lon
dtdf[nm] <- lapply(nm, function(x) geoloc[[x]][match(as.character(dtdf$city), as.character(geoloc$city))]) #apply it to trump dataset

set.seed(20000)
sample_trump <- bsdf[sample(1:length(dtdf$amount), 3000), ] #sample dataset for trump

largest_cities_dtdf <- subset(dtdf, city == c("BAKERSFIELD", "SAN JOSE", "LOS ANGELES","SACRAMENTO","SAN DIEGO", "HUNTINGTON BEACH")) #sanders contributions in bigger cities

refund_dtdf <- subset(dtdf, receipt == "Refund" & city == c("BAKERSFIELD", "SAN JOSE", "LOS ANGELES","SACRAMENTO","SAN DIEGO", "HUNTINGTON BEACH"))  # largest cities who obtained a refund.


largest_amount_dtdf <- subset(largest_cities_dtdf, amount > 0) #no refunds in dataset. 

head(dtdf) # look at dataset


############################################## Merge Dataset ###########################################################
merge_bs_dt_df <- merge(bsdf, dtdf, all = TRUE) # merge both datasets

summary(merge_bs_dt_df)

largest_cities_merge <- subset(merge_bs_dt_df, city == c("BAKERSFIELD", "SAN JOSE", "LOS ANGELES","SACRAMENTO","SAN DIEGO", "HUNTINGTON BEACH",
                                                         "OAKLAND", "BERKELEY", "SAN FRANCISCO")) # largest cities for both canidates

largest_amount_merge <- subset(largest_cities_merge, amount > 0) # no refunds in ammount


#box plot for both canidates. 
ggplot(aes(x = city, y = amount, fill = city), data = largest_amount_merge) +
  geom_boxplot() + labs(title = "Ordered Box Plot", 
                        subtitle = "Amount vs. City", 
                        caption = "source: .gov") + 
  scale_y_continuous(limits = c(0,200), breaks = seq(0,200,10)) + 
  facet_wrap(~canidate) 


#hisogram for both canidates.
theme_set(theme_bw())
ggplot(largest_amount_merge, aes(x=city, y=amount)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Ordered Bar Chart", 
       subtitle="Amount vs. City", 
       caption="source: gov") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
  facet_wrap(~canidate)


#create map for bernie v trump of contributors. 
head(ca_county)
ggplot(data = ca_county, aes(x = long, y = lat, group = group)) + 
  geom_polygon(fill = I("linen")) + 
  geom_path(aes(color = subregion), linestyle = 1) +
  geom_jitter(data = sample_bernie, aes(x =lon, y = lat, group= NULL), color = "blue", alpha = 1) + 
  geom_jitter(data = sample_trump, aes(x = lon, y = lat, group = NULL), color = "red", alpha = 0.3) + 
  labs(title = "Map of contributors", 
       subtitle = "Trump (red) v. Bernie (blue)", 
       caption= "source: .gov")  + 
       coord_map() 

  
```

# Summary of the Dataset


```{r echo=FALSE, summary}
str(largest_cities_bsdf) #19,118 objects and 9 varaibles within the summary.
summary(bsdf) #complete data set
summary(bsdf$amount) #summary of amount 
summary(dtdf)
summary(merge_bs_dt_df)
```

```{r echo=False, plot of bernie dataset}


#hisogram
theme_set(theme_bw())
ggplot(refund_bsdf, aes(x=city, y=amount)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Ordered Bar Chart", 
       subtitle="Amount vs. City", 
       caption="source: gov") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))

#boxplot
ggplot(aes(x = city, y = amount, fill = city), data = largest_amount_bsdf) +
  geom_boxplot() + labs(title = "Ordered Box Plot", 
                        subtitle = "Amount vs. City", 
                        caption = "source: .gov") + 
  scale_y_continuous(limits = c(0,200), breaks = seq(0,200,10))

#line graph
ggplot(data = largest_cities_bsdf, aes(date, amount)) + 
  geom_line(aes(color = city)) + 
  labs(title = "Line Graph Bernie Sanders", 
       subtitle = "Amount vs Date", 
       caption = "source: .gov") 


#cross validation matrix 
set.seed(2000) # set the seed at #2000
bsdf_samp <- bsdf[sample(1:length(bsdf$amount), 1000), ]
bsdf_sampII <- subset(bsdf_samp, select  = c(city, amount))
ggpairs(bsdf_sampII, 
        lower = list(continuous = wrap("points", shape = I("."))), 
        upper = list(continuous = wrap("box", outlier.shape = I("."))))  



#bsdf_state_sample <- subset(bsdf, select = c(city, amount, name)) #subset the datqframe for bernie
#bsdf_state_sample['region'] <- "california" #create a new column
#levels(bsdf_state_sample$city) <- tolower(levels(bsdf_state_sample$city)) #make city all lower case

#bsdf_state_sample
#str(ca_county)
#ca_county_ss <- subset(ca_county, select = c(region,long,lat))
#str(ca_county_ss)

#set.seed(20000)
#bsdf_state_sampleII <- bsdf_state_sample[sample(1:length(bsdf_state_sample$amount), 3000), ]
#bsdf_state_sampleII = rename(bsdf_state_sampleII, city = "subregion")
#test <- merge(ca_county,bsdf_state_sampleII, by = "subregion")


#bsdf_state_sampleIII <- subset(bsdf_state_sampleII, subregion == "ventura")
#bsdf_state_sampleII
```


# Trump Dataset
```{r echo=False, plot of trump dataset}

#line graph
ggplot(data = largest_cities_dtdf, aes(date, amount)) + 
  geom_line(aes(color = city)) + 
  labs(title = "Line Graph Donald Trump", 
       subtitle = "Amount vs Date", 
       caption = "source: .gov") 


#boxplot
ggplot(aes(x = city, y = amount, fill = city), data = largest_amount_dtdf) +
  geom_boxplot() + labs(title = "Ordered Box Plot", 
                        subtitle = "Amount vs. City", 
                        caption = "source: .gov") + 
  scale_y_continuous(limits = c(0,200), breaks = seq(0,200,10))

#hisogram
theme_set(theme_bw())
ggplot(refund_dtdf, aes(x=city, y=amount)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Ordered Bar Chart", 
       subtitle="Amount vs. City", 
       caption="source: gov") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))



```
```{r echo=False, create a bernie map}
str(bsdf)
```
