---
title: "problem_set_two_variable"
output: html_document
# Kris Anaya 
---

```{r price vs x}
library(ggplot2)
data(diamonds)
names(diamonds)
ggplot(aes(x = x, y = price), data = diamonds) + 
  geom_point() + xlim(3,9) #this scatter plot shows a exponential growth considering length to price. Meaning, the large the length the more the price. 
```
```{r correlations coeff}
with(diamonds, cor.test(price, x, method = "pearson"))
with(diamonds, cor.test(price, y, mehtod = "pearson"))
with(diamonds, cor.test(price, z, menthod = "pearson"))
# each dataset shows a positive correlation roughly similary between lengths of (x,y,z)
```

```{r price vs depth}
ggplot(aes(x = depth, y = price), data = diamonds) + 
  geom_point(alpha = 1/100) + 
  scale_x_continuous(breaks = seq(61, 63, 2))

summary(diamonds$depth) #must look at the relationship of the quartiles to see the lower and upper limits
#horizontal relationship within the graph position if price is x and depth is y. However if you transpose the grid then it's a verticle relationship. 

with(diamonds, cor.test(depth, price , method = "pearson"))
```

```{r price vs carat}
ggplot(data = diamonds,aes(x = carat, y = price)) + 
  xlim(0,quantile(diamonds$carat,0.99)) +
  ylim(0,quantile(diamonds$price,0.99)) +
  geom_point()

```




```{r price vs. volume}
library(plyr)
diamonds$volume <- (diamonds$x * diamonds$y * diamonds$z)
ggplot(data = diamonds, aes(x = volume, y = price)) + 
  geom_point()

count(diamonds$volume == 0)
detach("package:plyr", unload=TRUE)

pf_exclude_zero_eight <- subset(diamonds, !(volume == 0 | volume >= 800)) #conditional operator for subset! ALWAYS REMEMBER THIS
with(pf_exclude_zero_eight, cor.test(price, volume), method = "spearman")





```

```{r price vs volume}
pf_exclude_zero_eight <- subset(diamonds, !(volume == 0 | volume >= 800)) #exclude with conditional properties
ggplot(data = pf_exclude_zero_eight, aes(x = volume, y = price)) + 
  geom_point(alpha = .05) + #transparenct ar alpha 0.05
  geom_smooth(method = "lm") #adjust by linear model

```

```{r mean price clarity}
#install.packages("dplyr")
library(dplyr)
names(diamonds)
diamonds_clarity <- group_by(diamonds, clarity)
diamondsByClarity <- summarise(diamonds_clarity, 
                              mean_price = mean(price), 
                              median_price = median(price), 
                              min_price = min(price), 
                              max_price = max(price), 
                              n = n())
diamondsByClarity <- arrange(diamondsByClarity)
head(diamondsByClarity)
```
```{r bar chart clarity }
diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))

#install.packages("gridExtra")
library("gridExtra")

names(diamonds_mp_by_clarity)

p1 <- ggplot(diamonds_mp_by_clarity, aes(x = clarity, y = mean_price)) + geom_bar(stat = 'identity')
p2 <- ggplot(diamonds_mp_by_color, aes(x = color, y = mean_price)) + geom_bar(stat = "identity")
grid.arrange(p1,p2)

names(diamonds_mp_by_color)
?diamonds
```

